### ISSUE TITLE
Rust codegen doesn't handle the `any` type.

### ISSUE THREAD

**Issue by jsoverson** [apexlang/codegen#18]
## Actual

When trying to codegen anything with an `any` type, the Rust codegen fails with an error.

```shell-session
$ apex generate
Generating src/generated.rs...
Generation error: Unhandled primitive type conversion for type: any 
```

## Expected

Codegen to work without error.

## To reproduce

Use the following apex source.

```apexlang
namespace "issue"

type MyStruct {
  this: any
}
```

And any config that uses the rust codegen, e.g.

```yaml title="apex.yaml"
spec: ./issue.apexlang
generates:
  src/generated.rs:
    module: "@apexlang/codegen/rust"
    visitorClass: RustBasic
```

And run `apex generate`
